oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/templates/oh_staff_ui/item_search.html, oh_staff_ui/templates/oh_staff_ui/search_results.html, oh_staff_ui/urls.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py, static/css/style.css
Implements [SYS-1178](https://jira.library.ucla.edu/browse/SYS-1178)
Creates basic search functionality for ProjectItems. After login, the search form (http://127.0.0.1:8000/item_search/) allows users to search by ARK or Title, finding case-insensitive substring matches for each. The results are displayed on a new search_results page, sorted alphabetically by ARK or Title depending on the type of search performed. Each result ARK contains a link to the corresponding /item/item_id page.
Let me know if we should have more/different functionality at this stage (different types of result sort or search matching? more Item metadata in the results display?) - thanks!
=> SYS-1178: Basic item search interface

README.md, oh_staff_ui/forms.py, oh_staff_ui/models.py, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/views.py, oh_staff_ui/views_utils.py
Implements [SYS-1179](https://jira.library.ucla.edu/browse/SYS-1179).
This PR adds support for editing items and specific types of optional metadata (names and subjects, for now).  It establishes a basic "framework" for supporting other optional metadata:
* Define a "usage form" in `forms.py` which supports data for a "usage model".  For example, `NameUsageForm` supports the `ItemNameUsage` model.
* Name & Subject forms use fully-controlled types and values backed by other models.
* Some other forms will need to use controlled types, but uncontrolled values.
* Add code to `views_utils.py` which
* Creates and populate a formset with existing values; see `get_name_formset()` and `get_subject_formset()`.
* Adds the formset to `get_edit_item_context()`, so it can be passed to the …
=> SYS-1179: Add support for item editing

.docker-compose_django.env, oh_staff_ui/templates/oh_staff_ui/add_item.html, oh_staff_ui/views.py, oh_staff_ui/views_utils.py, project/settings.py, requirements.txt
Implements [SYS-1174](https://jira.library.ucla.edu/browse/SYS-1174).
This PR adds a `get_ark()` method to `views_utils.py`.  This method is called by the `add_item()` view.
If running in the `dev` environment, `get_ark()` returns a mock ARK, with prefix of `FAKE/` followed by 10 random(ish) hex characters, like `FAKE/249dd89b20`.  Otherwise, `get_ark()` tries to obtain a real ARK from our ARK minter service.  This can fail - the service may be unavailable, or forbidden due to IP address restrictions - in which case an `HTTPError` is thrown and logged:
```
CRITICAL 2023-03-16 20:11:28,881 oh_staff_ui.views_utils views_utils 403 Client Error: Forbidden for url: http://noid.library.ucla.edu/noidu_zz8+?mint+1
```
The `add_item()` view wraps the creation of a new item in a `try/except` block. …
=> SYS-1174: Add real and mock ARK support

oh_staff_ui/forms.py, oh_staff_ui/models.py, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/views_utils.py
Implements [SYS-1189](https://jira.library.ucla.edu/browse/SYS-1189).
This PR adds 3 fields to the `edit_item` template:
* coverage (free text, editable)
* status (controlled list, editable)
* parent (link, if parent exists, not editable)
A `get_default_status()` method was added to `models.py` to support the need for "In progress" to be the default status.  I also fixed the existing default type, so it now uses the `get_default_type()` method.
* Load full set of project item data, if not already done:
`$ docker-compose exec django python manage.py import_projectitems oh-projectitems-export-3.csv`
* Do a search, like http://127.0.0.1:8000/search_results/title/allen
* View a few records. Interviews and legal agreements generally are children, so there should be a parent link.  Series are …
=> SYS-1189: Add coverage, status and parent info to item editing screen

README.md, docker_scripts/nuke_dev_db.sh
Implements [SYS-1199](https://jira.library.ucla.edu/browse/SYS-1199).
This PR adds a simple shell script, `docker_scripts/nuke_dev_db.sh`, which can be run to reset the local docker-based development database.  It does the following:
* Shuts down the application
* Drops the docker volume for the database
* Starts the application
* Reloads data files via management commands.
* This currently is just `ProjectItem` and `Name` files; others will be added as loaders are finished.
Developers can opt out of reloading data by adding a specific parameter:
`docker_scripts/nuke_dev_db.sh NOLOAD`
`README.md` is updated with this information.
=> SYS-1199: Add script to reset local development database

oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/templates/oh_staff_ui/item_tree.html, oh_staff_ui/views_utils.py, static/css/style.css
Implements [SYS-1180](https://jira.library.ucla.edu/browse/SYS-1180)
This PR adds a "local hierarchy" display to item edit pages. This hierarchy is presented in a collapsible tree up to the Series level. Users can expand and collapse the tree and use links to navigate to related items.
I've set this as a draft PR for now since I have a few concerns about my solution:
* The recursive item_tree template may be overcomplicated and difficult to maintain.
* We could probably use more styling to highlight what page we're currently on in the hierarchy.
* I'm not sure how far the tree should be "open" by default. Currently, the Series is always expanded, as is the immediate parent of the current item. "Interview" level items are not expanded by default, but displayed alongside siblings.
* This …
=> SYS-1180: Display hierarchy on item edit pages

.docker-compose_db.env, .docker-compose_django.env, .github/workflows/push_helm_chart.yml, charts/.helmignore, charts/Chart.yaml, charts/prod-ohstaff-values.yaml, charts/templates/NOTES.txt, charts/templates/_helpers.tpl, charts/templates/configmap.yaml, charts/templates/deployment.yaml, charts/templates/externalsecret.yaml, charts/templates/ingress.yaml, charts/templates/namespace.yaml, charts/templates/pv-ohmasters.yaml, charts/templates/pv-ohsource.yaml, charts/templates/pv-ohstatic.yaml, charts/templates/pv-ohwowza.yaml, charts/templates/pvc-ohmasters.yaml, charts/templates/pvc-ohsource.yaml, charts/templates/pvc-ohstatic.yaml, charts/templates/pvc-ohwowza.yaml, charts/templates/secrets.yaml, charts/templates/service.yaml, charts/values.yaml
Implements [SYS-1200](https://jira.library.ucla.edu/browse/SYS-1200).
This PR adds an initial version of the Helm chart for the Oral History Staff UI application, `oh-staff`.  It's intended for deployment in our production Rancher Kubernetes environment.
There are two external secrets defined.  Both have been created in our AWS parameter store.
This application will need access to the same persistent volumes as the existing [`dlcs-staff-ui`](https://github.com/UCLALibrary/dlcs-staff-ui/tree/main/charts) application, so I copied those templates as-is, changing just the application name/variables.  This application will also need similar resources allocated, so I also used that data.
=> SYS-1200: Initial version of Helm chart

oh_staff_ui/urls.py
Implements [SYS-1186](https://jira.library.ucla.edu/browse/SYS-1186)
Changing the URL converter from `str` to `path` now allows search terms including forward slashes. Useful for full ARK search and title searches including dates (e.g. 11/18/2020).
=> SYS-1186: Fix error when searching for full ARK

oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/urls.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py
Implements [SYS-1212](https://jira.library.ucla.edu/browse/SYS-1212)
These changes allow any ProjectItem with Type "Series" or "Interview" to be selected as the parent when adding a new item. This is done with a dropdown field at the top of the add_item form. 
Additionally, a new link called "Add a child item" has been added to the top of the item display page for Series and Interviews. Clicking this link should take the user to the add_item form with the Parent dropdown already set. 
This does not allow moving children to new parents at this point.
=> SYS-1212: Allow parent to be specified when adding new records

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/views_utils.py, static/css/style.css, static/js/main.js
Implements [SYS-1204](https://jira.library.ucla.edu/browse/SYS-1204).
This PR adds dynamic repeatable fields to the item editing form.  It allows the editor to create any number of names, subjects, descriptions etc., without having to save and submit the form after each one.  It does this by using javascript to clone a hidden Django `formset.empty_form`.  The javascript updates the DOM and the hidden `TOTAL_FORMS` value which Django uses to confirm the correct number of sets of form data was received.
The `edit_item` template now has an extra row for each metadata type, like `<tr id="name_empty_form" class="empty_form">`.  This is largely duplicate code, but I don't see a way to output both the "real" form data for display and the hidden empty form, using Django's template language, …
=> SYS-1204: Enable dynamic repeatable fields

oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/templates/oh_staff_ui/edit_item.html, static/js/validation.js
Implements [SYS-1205](https://jira.library.ucla.edu/browse/SYS-1205)
Adds a javascript function to the edit_item form that checks, for metadata fields with both a "qualifier" and "value", that either neither or both fields has been filled out. If exactly one of the two fields has a value, a browser alert is shown indicating the metadata type needing review and the form is not submitted. 
Currently, only one problem is reported at a time, so users may need to revise their input multiple times before a submission is successful.
=> SYS-1205: javascript validation for edit_item form

README.md, charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/templates/oh_staff_ui/log.html, oh_staff_ui/urls.py, oh_staff_ui/views.py
Implements [SYS-1233](https://jira.library.ucla.edu/browse/SYS-1233).
This adds a basic way to view the application log via browser, which is mainly useful with the deployed application, since developers do not currently have access to production containers or their logs.
By default, the latest 200 lines of the application log can be viewed at `/logs/`.  This can be changed by editing the URL; for example, `/logs/500` would show the latest 500 lines of the log.
Added this info to `README.md`.
Bumped version to `v0.4.5` for deployment.
=> SYS-1233: Show logs in web UI

charts/prod-ohstaff-values.yaml, oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/templates/oh_staff_ui/upload_file.html, oh_staff_ui/urls.py, oh_staff_ui/views.py, samples/fake_file_01.wav, samples/fake_file_02.wav, samples/fake_file_03.wav, samples/fake_file_04.wav, samples/fake_file_05.wav, samples/fake_file_06.wav, samples/fake_file_07.wav, samples/fake_file_08.wav, samples/fake_file_09.wav, samples/fake_file_10.wav, samples/managed/.gitignore, static/js/main.js
Implements [SYS-1228](https://jira.library.ucla.edu/browse/SYS-1228); bumps version to `v0.5.0`.
This PR adds the ability for editors to select and "upload" files, associating them with items.  Files are not really uploaded (transferred from local machine via browser & network to server); instead, the user selects a file from a hard-coded directory on the server itself.  This reuses functionality from the phase 1 project.
For now, files are selected via form at `/upload_file/<item_id>`.  Users can switch between file and metadata forms by clicking `View metadata` or `View files`.
This does not implement file processing (converting audio wav files to mp3, or image tiffs to jpeg, etc.).  For now, the selected file is simply copied to the `samples/managed/` subdirectory, renamed, and a new …
=> SYS-1228: Implement basic file saving

oh_staff_ui/admin.py
Implements [SYS-1235](https://jira.library.ucla.edu/browse/SYS-1235)
All lookup tables and controlled value lists are now sorted alphabetically by default within the admin interface. When more than one column is visible, data is sorted in order of the columns left to right.
No migrations or other special testing instructions - just log in to the admin interface and view the data for each available model.
=> SYS-1235: Apply default sorts to data in Admin interface

oh_staff_ui/forms.py, oh_staff_ui/models.py, oh_staff_ui/templates/oh_staff_ui/upload_file.html, oh_staff_ui/tests.py, oh_staff_ui/views.py, static/css/style.css
Implements [SYS-1239](https://jira.library.ucla.edu/browse/SYS-1239).
This PR prevents the same file from being associated with a given item multiple times.  If an editor tries, Django does not save the new `MediaFile`, and shows a message like this:
A new test was added which covers this.
Other changes include minor improvements to the file upload form display, and some code formatting changes and other minor cleanup.
Testing:
* Add a file to an item.
* Try to add the same file again to the item.  It should not be added, and a message to that effect should appear.
=> SYS-1239: Prevent duplicate uploads

oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/edit_item.html, static/css/style.css
Implements [SYS-1240](https://jira.library.ucla.edu/browse/SYS-1240)
Template, form, and CSS changes intended to give the edit item pages a more cohesive and comprehensible appearance. No functionality changes.
Please test in a couple of different browsers if you can. There are a number of differences between the page's appearance in Firefox and Chrome as it stands - let me know if I should better harmonize these. I've attempted to size things to comfortably fit items with long titles (like 21198/zz002jxz6f).
=> SYS-1240: Improve "edit item" page appearance

oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/urls.py, static/css/style.css, templates/admin/base_site.html
Implements [SYS-1241](https://jira.library.ucla.edu/browse/SYS-1241)
This PR styles the menu links on each page of the site as a navbar, and adds an additional link from the admin interface to the main site. I'd particularly appreciate feedback about the wording of the links - right now I'm using "Admin (Metadata Configuration)" to link to the admin interface, and "Main Oral History Staff Interface" to link back to the main site. 
Also, there is a preexisting link to the site in the admin interface header ("view site"). I think it's useful to have the link displayed more prominently and with better wording even if it's redundant, but let me know if I should remove the old one. 
Main site header:
Admin header:
=> SYS-1241: Improve links menu and admin navigation

charts/prod-ohstaff-values.yaml, oh_staff_ui/fixtures/item-type-data.json, oh_staff_ui/forms.py, oh_staff_ui/models.py, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/tests.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py
Implements [SYS-1256](https://jira.library.ucla.edu/browse/SYS-1256).
This PR makes improvements to item types:
* Remove unused `Collection` type from the `item-type-data` fixture.
* `Series` is now the top-level item type; otherwise, the hierarchy is unchanged.
* Allow only appropriate item types to display via `ProjectItemForm`, used for adding and editing "pure" item data (not the optional metadata).
* The only item type allowed for top-level items is `Series`
* The only item type allowed for 2nd-level items is `Interview`
* The only item types allowed for 3rd-level items are `Audio` and `Video`, with `Audio` as the default
* Removed the now-obsolete `get_default_type()` method, which always set `Audio` on the form.
* Update existing tests to use real `ItemType` objects instead of id …
=> SYS-1256: Item type cleanup

oh_staff_ui/classes/OralHistoryFile.py, oh_staff_ui/tests.py
Implements [SYS-1248](https://jira.library.ucla.edu/browse/SYS-1248).
This PR adds an internal method to `OralHistoryFile` which validates the content type against the file type.  If the check fails, a `ValueError` is raised.
Examples:
* Uploading "file.pdf" but selecting "MasterAudio1" should throw an error
* Uploading "file.wav" and selecting "MasterAudio1" should be accepted.
Testing:
4 new tests were added, checking `audio`, `image`, `pdf`, and `text` (content type) input files against a mismatched file type (e.g., `sample.wav` (audio) against `pdf_master` (pdf).
* No restart necessary.
* `$ docker-compose exec django python manage.py test` should show 52 tests, all passing.
* Pick a random item, like http://127.0.0.1:8000/upload_file/7647, and try to upload a similar mismatch.
* …
=> SYS-1248: Validate content type against file type

oh_staff_ui/templates/oh_staff_ui/edit_item.html, static/css/style.css, static/js/main.js
Implements [SYS-1257](https://jira.library.ucla.edu/browse/SYS-1257)
This PR hides all optional metadata fields other than Description on Audio/Video ProjectItems. In addition, the only visible qualifier is TableOfContents. Styling is done with CSS, with accompanying changes to the template and JS to add class values. 
One question: should adding multiple Descriptions on file-level items be supported? This is possible for now (though all must be TableOfContents), but we could also hide the plus button.
=> SYS-1257: Hide metadata fields on file-level items

static/js/main.js
Implements [SYS-1273](https://jira.library.ucla.edu/browse/SYS-1273)
Instead of checking that the current page's URL contains "item_search" (which missed the home page search form), `main.js` now checks for the existence of the item_search form before executing the code specific to this page. This fixes the duplicated "Query:" label, and Status search now works directly from the homepage.
=> SYS-1273: 

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py, requirements.txt
Very basic PR to confirm install and base behavior
- [eulxml](https://eulxml.readthedocs.io/) added to requirements.txt
- `OralHistoryMods` class added extending base `eulxml.xmlmap.mods.MODS` class
- Tests added to validate empty MODS records pass for each item type
This PR is primarily to confirm libraries are installed and able to be tested properly.
To confirm run:
`docker-compose exec django python manage.py test`
All tests should pass if the `eulxml` library is properly installed and a valid empty MODS record can be created for each item type. Jira ticket will be updated to reflect the stripped down PR.
For now the version of eulxml is `1.1.3` rather than the most recent github commit, to be revised if required.
ply version `3.11` added to resolve warning.
=> Initial add of MODS export libraries and tests

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py
Basic PR to rework some tests and add an ARK as an identifier field in a MODS record
Some very slight changes to OralHistoryMods class
- Constructor accepts `ProjectItem` record rather than an id
- `populate_fields` public function intended to house each function to populate a field
- `_populate_identifier` private function that other MODS fields will follow a similar pattern
- Tests updated to reflect constructor changes
This PR is basic to get template ironed out, the remainder of fields will follow a similar pattern, a private function that performs any logic required to populate that particular MODS field, then added to the `populate_fields` function with related tests.
=> Adding ark as identifier to MODS record

oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/base.html, static/js/main.js
Implements [SYS-1263](https://jira.library.ucla.edu/browse/SYS-1263)
Adds a small amount of conditional JS to hide Parent dropdown and label on the base `add_item` page (i.e. for new series creation). Dropdown and label are still visible after following link to add a child item, and on `edit_item` pages. Base template is also updated to change `add_item` link to read "Add Series".
=> SYS-1263: Hide Parent drop-down on add_item form page

oh_staff_ui/classes/OralHistoryMods.py
For consistency moved MODS title assignment to own private function in `OralHistoryMods`
No additional requests are required for MODS validation, the existing test suite can be run to verify valid:
`docker-compose exec django python manage.py test`
=> Moved MODS title assignment to own function

oh_staff_ui/templates/oh_staff_ui/add_item.html, oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/templates/oh_staff_ui/item_search.html, oh_staff_ui/templates/oh_staff_ui/search_results.html, oh_staff_ui/templates/oh_staff_ui/upload_file.html, project/settings.py, requirements.txt, static/css/style.css
Implements [SYS-1296](https://jira.library.ucla.edu/browse/SYS-1269)
Applies Bootstrap styling to the OH Staff UI application using `django-bootstrap5`. To test, restart your Django container to install the new package requirement, then marvel at the new post-Y2K-looking site. Please test both appearance and functionality, as many of the changes interact with our JS.
The styling is largely default Bootstrap, so there is room for improvement. I have a couple of questions here:
* Form fields are larger and more spaced out now. This is probably easier to read, but also means more scrolling for long `edit_item` pages. Should we try reducing the vertical space between form fields?
* Blank text fields now contain placeholder text. I can't tell if the default color of the text is dark enough to …
=> SYS-1296: Style with Bootstrap 5

charts/prod-ohstaff-values.yaml, oh_staff_ui/models.py, oh_staff_ui/templates/oh_staff_ui/upload_file.html, oh_staff_ui/tests.py
Implements [SYS-1281](https://jira.library.ucla.edu/browse/SYS-1281).
Bumps version to `v0.9.2` for deployment.
This PR adds a new property on the `MediaFile` model, `file_url`.  This is calculated based on the full path to the file (relative to the container), which is available via `MediaFile.file.name`.  The URL is not stored in the database, and cannot be queried - it's only available via an instance of `MediaFile`.
`MediaFile.file_url` currently is determined only for non-masters, pending policy and technical decisions about future access to master files.  It also has meaning only for production files (whether in production environment, or data loaded in dev environment), since all real files are accessed by separate production web servers.
There's also a new property, …
=> SYS-1281: Add URLs for non-master file access

.docker-compose_django.env, README.md, charts/Chart.yaml, charts/prod-ohstaff-values.yaml, charts/templates/configmap.yaml, charts/values.yaml, media_dev/.gitignore, media_dev/oh_lz/.gitignore, media_dev/oh_static/.gitignore, media_dev/oh_wowza/.gitignore, oh_staff_ui/management/commands/import_file_metadata.py, oh_staff_ui/migrations/0004_mediafile_mediafiletype_and_more.py, oh_staff_ui/models.py, oh_staff_ui/tests.py, project/settings.py
Implements [SYS-1286](https://jira.library.ucla.edu/browse/SYS-1286). Bumps version to `v0.9.3` for deployment.
This PR fixes a major bug which prevented file uploads from working in the production environment.  The bug was caused by my misunderstanding of Django's `FileField` and its `upload_to` functionality, along with a significant difference in where uploaded files go, between development and production environments.
I thought that `MediaFile.file(upload_to="/some/absolute/path/to/file")` would (a) work, and (b) mean that Django's `MEDIA_ROOT` didn't need to be defined.  Both were wrong :(
`MEDIA_ROOT` defaults to `''`, meaning the top-level directory in the project.  In the development environment, files were going to `media_dev/` - in the top-level directory - with relative paths …
=> SYS-1286: Fix file handling

charts/prod-ohstaff-values.yaml, docker_scripts/entrypoint.sh
Implements [SYS-1287](https://jira.library.ucla.edu/browse/SYS-1287).  Bumps version to `v0.9.4` for deployment.
This PR fixes a problem seen when processing larger audio files, by extending the `gunicorn` worker process timeout from 60 seconds to 600 seconds (10 minutes).
This is intended as a workaround, until proper asynchronous file processing is added.
=> SYS-1287: Extend gunicorn worker process timeout

charts/prod-ohstaff-values.yaml, oh_staff_ui/forms.py, oh_staff_ui/tests.py
Implements [SYS-1277](https://jira.library.ucla.edu/browse/SYS-1277).  Bumps version to `v0.9.5` for deployment.
This PR improves item creation by providing an appropriate default value for sequence, when adding an item via `/add_item/` or `/add_item/<parent_id>`.  Item sequence is a required field, but often not used or desired, so manually providing a default is a nuisance.  Users can accept the default, or change it to another value, as desired.
* If the new item is a Series or Interview, the default is always 1.
* If the new item is a File (Audio or Video), the default is the max sequence used by other child items of the same parent (if any), plus 1.
* When editing an existing item, whatever is already stored in the item sequence field will display, as always.
Testing:
Two new tests …
=> SYS-1277: Provide appropriate default sequence when adding items

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py
Adding PR for each element going forward, future PRs may reference a previous ticket.
This adds tests and support for `mods:dateCreated`. 
Our existing MODS records generation process only outputs those date fields with the `creation` qualifier, so I am following that pattern here by filtering only on this type.
A test added to confirm the record validates and the correct element is in the xml.
To confirm, run tests to verify basic example.
To verify with similar process as previous MODS pr:
```
>>> from oh_staff_ui.classes.OralHistoryMods import OralHistoryMods
>>> from oh_staff_ui.models import ProjectItem
>>> pi = ProjectItem.objects.get(id=2207)
>>> ohm.serializeDocument()
b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<mods:mods …
```
=> Addition of creation date element

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py
Addition of AltTitle mods element.
If an AltTitle record is present an additional `mods:titleInfo` field will be created with type of `alternative`.
Testing:
`AltTitle` is not as common as other fields, so a quick way is to edit a record to add an AltTitle with any qualifier, and confirm via shell using similar calls as previous PR.
```
>>> pi = ProjectItem.objects.get(id=2207)
>>> ohm.serializeDocument()
```
A test has been added to check for the presence of `titleInfo` along with an attribute type `alternative`, different from the standard `title` field.
=> Addition of alternate title mods element

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py
Addition of AltId mods element.
Testing:
Either add alternate id or use an existing record with one, there are a handful with `OPAC` types
Interview of Cecil Talney - `id=1482`, this may not be same in local DB.
```
>>> pi = ProjectItem.objects.get(id=1482)
>>> ohm.serializeDocument()
```
A test has been added to check for the presence of identifier along with an assigned attribute
=> Addition of test and alt identifier mods element

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py
Addition of Copyright mods element.
Testing and confirmation:
The previous item may still be used to test, or any others that have a copyright field populated.
Title: Interview of Cecil Talney - id=1482
```
>>> pi = ProjectItem.objects.get(id=1482)
>>> print(ohm.serializeDocument())
```
The relevant tag is:
```<mods:accessCondition>Interviewee Retained Copyright</mods:accessCondition>```
A test has been added to check for the presence of the `accessCondition` tag
=> Addition of copyright mods element and test

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py
Addition of `Name` and related MODS elements and test
To confirm, run tests, which looking for existence of 2 elements that are constructed when adding a name.
Also confirm via an item that the XML is generated correctly for database data. The same item maybe be used as previously.
```
>>> from oh_staff_ui.models import ProjectItem
>>> from oh_staff_ui.classes.OralHistoryMods import OralHistoryMods
>>> pi = ProjectItem.objects.get(id=1482)
>>> print(ohm.serializeDocument())
b'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<mods:mods xmlns:mods="http://www.loc.gov/mods/v3"><mods:titleInfo><mods:title>Interview of Cecil Talney</mods:title></mods:titleInfo><mods:note type="supportingdocuments" displayLabel="Supporting Documents">Records …
```
=> Addition of mods name element and test

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/tests.py
This adds tests and support for mods:subject and completes generation of non-file elements directly attached to a `ProjectItem` (SYS-1207)
Previous logic had a few quirks:
- An option to exclude subjects that match particular values
- The `AuthoritySource` lowercase is used as the authority
- The qualifier is not used in the output
A test added to confirm the record validates and the correct element is in the xml.
To confirm, run tests to verify basic example.
To verify with similar process as previous MODS pr:
```
>>> from oh_staff_ui.classes.OralHistoryMods import OralHistoryMods
>>> from oh_staff_ui.models import ProjectItem
>>> pi = ProjectItem.objects.get(id=2207)
>>> ohm.serializeDocment()
>>> print(ohm.serializeDocument()) …
```
=> Addition of subject mods element and test

oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/templates/oh_staff_ui/order_files.html, oh_staff_ui/urls.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py
Implements [SYS-1210](https://jira.library.ucla.edu/browse/SYS-1210)
On interview-level items only, adds a link ("Configure file order") to a new template (`order_files`) containing a form allowing users to edit sequence numbers on child ProjectItems.
This form does not enforce any new validation on sequence numbers, i.e. users can still enter duplicate sequence numbers, numbers < 1, etc. Changing a sequence number via this form will also update the modified date and modified by fields on the associated item. 
Screenshots:
---
=> SYS-1210: Easier editing of file-level item sequence numbers

oh_staff_ui/templates/oh_staff_ui/search_results.html, oh_staff_ui/views.py, static/css/style.css
Implements [SYS-1290](https://jira.library.ucla.edu/browse/SYS-1290)
Small view, template, and CSS changes to support display of item Parent in search results. Some notes:
* Parents are not currently linked, in keeping with how Title is displayed.
* If an item has no parent, the Parent column is empty.
* Using Bootstrap table styling was easier than dealing with potentially very long lines with text wrapping, so I've applied that to the search results table and removed two now-unused CSS rules.
=> SYS-1290: Add parent title to search results

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/edit_item.html, static/css/style.css
Implements [SYS-1296](https://jira.library.ucla.edu/browse/SYS-1296).
Bumps version to `v0.9.7` to deploy this and other recent UI changes.
This PR changes the label from `Resource(s)` to `Type(s) of Resource` in the `edit_item` template.  It also tweaks the CSS to prevent the longer label text from wrapping.
Testing: No automated tests.  Look at http://127.0.0.1:8000/item/251 or any other item to see the new wording and confirm the label text does not wrap.
=> SYS-1296: Change resource label on item editing form

charts/prod-ohstaff-values.yaml, oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/search_results.html, oh_staff_ui/views.py, oh_staff_ui/views_utils.py
Implements [SYS-1292](https://jira.library.ucla.edu/browse/SYS-1292).  Bumps version to `v0.9.8` for deployment.
This PR adds item type (currently Series, Interview, Audio) to the search results, to make the context of each result clearer.
The original code handled keyword search results differently from other search types, with the `search_results` view and template both needing to account for this difference.  As part of this PR, the logic moves from the view & template to a new utility function, `views_utils.get_search_results()`  This returns consistent data, an appropriately-sorted list of items, so the view can just pass that data to the template for uniform display.
Testing:
No new (or old) automated tests; all tests still pass.
Do searches of different types to confirm `Type` now …
=> SYS-1292: Show item type in search results

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/management/commands/create_mods_records.py, oh_staff_ui/tests.py
This adds a management command and test and write a single record to a public mods directory specified by `ProjectItem.id`. A future PR on this same ticket will add management options and test for bulk export, calling similar functions.
The exported file name is the item ark with `/` swapped for `-` and `-mods.xml` appended. 
A full filename would look like:
`21198-zz00123456-mods.xml`
This is written to the static root directory under a `mods` subdirectory.
`{MEDIA_ROOT}/{OH_STATIC}/mods/{filename}.xml`
If a file exists, it is overwritten without warning.
To confirm proper behavior:
- Run tests, all should pass. Additional test writes a sample object mods record and checks for existence, calling the write function directly, as opposed to the management command
- Run the …
=> Sys 1211/management cmd mods export

oh_staff_ui/management/commands/create_mods_records.py
This adds PR bulk export MODS option via django management command.
A user may export single items with no restrictions via the `--item` option, or may use `--bulk` with a select number of item types to export MODS record in bulk. 
The bulk options include:
- series
- interview
- audio
- all
If there is a problem writing a record in a bulk setting, the `CommandError` is captured, the `ProjectItem.id` collected, and the remainder of the `ProjectItem` list is exported. The user is shown a result message at the end of operation.
Usage and testing:
The MODS writing logic has not changed, so an additional test has not been added.
To test the management command, run the following:
`docker-compose exec django python manage.py create_mods_records -b series`
Assuming a full test database, the …
=> Reworked mods export management command, added bulk options

oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/models.py, oh_staff_ui/tests.py, oh_staff_ui/urls.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py
This implements:
- SYS-1308 : Add OAI envelope
- SYS-1310 : Add GetRecord url option
- SYS-1311 : Add ListRecords url option
This replaces the core functionality of providing OH content via an OAI like endpoint, in order to deprecate the fragile current dldataprovider app and prevent the need for use of a stand alone OAI provider. 
Some feedback is appreciated, as some of the django best practices have not been followed, rather the OAI format for urls, but since there is only 1 client, I think we have some flexibility here.
A url parameter `verb` is required in the query string, this is the only required parameter, though it does not make sense without an `identifier` parameter as well for `GetRecord`
Example of use in the previous system: …
=> Sys 1308/oai envelope

README.md, charts/prod-ohstaff-values.yaml, docker-compose_REMOTE.yml, oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/urls.py, oh_staff_ui/views.py
Implements [SYS-1369](https://jira.library.ucla.edu/browse/SYS-1369), while bringing two other minor issues along:
* [SYS-1345: Prevent fixtures from being reloaded in production](https://jira.library.ucla.edu/browse/SYS-1345)
* [SYS-1234: Display application version (via release notes)](https://jira.library.ucla.edu/browse/SYS-1234)
This PR fixes a problem where the item metadata form limited Description text entry to 1024 characters, instead of allowing the full 8000 characters the model supports.  Migrated Description data includes values nearly 4000 characters long, and Oral History staff occasionally need to add very long tables of contents.
Since this was a very minor technical change which needed to be done, I combined it with two other minor issues which might otherwise not get …
=> SYS-1369: Increase form field limit for description text

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/AudioFileHandler.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py
Fixed [SYS-1416](https://uclalibrary.atlassian.net/browse/SYS-1416).
Tagged as version `v1.0.3` for release.
This PR fixes a bug in the `AudioFileHandler` class, which incorrectly set the `MediaFileType` of audio submaster files as masters instead.  It also adds a test to confirm this.
[SYS-1416]: https://uclalibrary.atlassian.net/browse/SYS-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SYS-1416: Fix audio_submaster bug

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html
We had reports of cases when an item had both a title and an alternate title, the title would not be generated correctly.
This turned out to be an issue of title and alt title creation ordering in the MODS creation process and inappropriately creating an additional `titleInfo` container.
To test:
All existing tests should continue to pass
Confirm item with alt title is generated correctly:
http://localhost:8000/oai/?verb=GetRecord&identifier=21198/zz0008zd21
```
<mods:titleInfo>
<mods:title>Interview of Friedrich A. Von Hayek</mods:title>
</mods:titleInfo>
<mods:titleInfo type="alternative">
<mods:title>Nobel Prize-Winning Economist</mods:title>
</mods:titleInfo>
```
Confirm item without alt title is also generated correctly:
http://localhost:8000/oai/?verb=GetRecord&identifier=21198/zz002 …
=> Combined title and alttitle generation to resolve bug

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/views_utils.py
Implements [SYS-1426](https://uclalibrary.atlassian.net/browse/SYS-1426).  Tagged as `v1.0.5` for release.
This PR fixes a bug which prevented items with status `Completed with minimal metadata` from being published via OAI.
There's also a little reformatting / cleanup of `views_utils.py` to make flake8/black happy.
[SYS-1426]: https://uclalibrary.atlassian.net/browse/SYS-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SYS-1426: Include 'Completed with minimal metadata' items in OAI feed

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py
Implement [SYS-1529](https://uclalibrary.atlassian.net/browse/SYS-1529).  Bumps version to `v1.0.6` for deployment.
This PR fixes a bug which allowed non-Completed File-level item metadata, including media URLs, to be included in the OAI feed.  For Sealed items which must not be published, this could expose sensitive information.
The fix itself adds a check on item status to `OralHistoryMods._populate_constituent_audio()`, to allow only Completed File-level item metadata to be added to the MODS record.
There also are several new tests which verify that Completed items are included, and non-Completed (specifically Sealed) items and metadata are excluded.  Since these tests require checking specific XML data, several utility test methods were added to make it easier to access the relevant …
=> SYS-1529: Prevent Sealed item information from being included in OAI feed.

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py
The public site expects TEI transcripts to have a `mods:location/mods:url[@usage="timed log"` attribute present in order to trigger specific functionality. This was removed in the initial implementation -- this commit adds it back.
This attribute value is not part of the [MODS specification](https://www.loc.gov/standards/mods/userguide/attributes.html#usage) for the location element, so no validation against the schema is done, either in tests or the application.
A minor change was made to the `OralHistoryMods` class, along with an additional test which confirms if a TEI transcript (filetype of `text_master_transcript`) is present, a `<mods:url usage="timed log">` tag is also present.
To test:
- Run tests, all should pass
- Generating an OAI record of an item that contains a TEI xml media …
=> Timed log attribute added for TEI XML transcripts with test

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/release_notes.html
Implements [SYS-1577](https://uclalibrary.atlassian.net/browse/SYS-1577).  Bumps version tag to `v1.0.9` for deployment.
This PR adds an internal host to Django's `ALLOWED_HOSTS` list, which will allow for more efficient networking between this staff application and the public application within our Kubernetes environment.
The new host was not added to `CSRF_TRUSTED_ORIGINS` as it will be used only for OAI-related `GET` requests, which should not be relevant for CSRF protection.
[SYS-1577]: https://uclalibrary.atlassian.net/browse/SYS-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SYS-1577: Add internal host for improved OAI harvesting

charts/Chart.yaml, charts/prod-ohstaff-values.yaml, charts/templates/configmap.yaml, charts/values.yaml
We are provided a list of host names to the `allowed_hosts` value and it appears the way we were passing these to the configmap template using the `range` loop was not working correctly. 
Since Django is expecting a comma-separated list in projects.yaml, we'll just provide that in the values file.
=> Adjust allowed_hosts value to be a comma-separated string

.github/workflows/build_docker_hub.yml
No need to run the docker build/push github action when we are only making changes within the helm charts directory.
=> Ignore helm charts directory when determining when to run docker build gh action

charts/Chart.yaml, charts/prod-ohstaff-values.yaml, charts/templates/_helpers.tpl, charts/templates/configmap.yaml, charts/templates/pv-ohmasterslz.yaml, charts/templates/pvc-ohmasterslz.yaml, charts/values.yaml
The changes here allow for mounting both the original OH Master Landing Zone volume and the new OH Masters volume. 
Once we confirm using the new OH Masters volume is working as-expected, we can remove the Landing Zone volume. 
@akohler Please review these changes when you get a chance, in particular the changes I made in `prod-ohstaff-values.yaml` and the `configmap.yaml`.
=> SYS-1594 Adjustment to mount the OH masters volume

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py
This PR addresses: 
- [SYS-1574](https://uclalibrary.atlassian.net/browse/SYS-1574) Image shows up in download options
- [SYS-1575](https://uclalibrary.atlassian.net/browse/SYS-1575) XML transcript does not appear in individual item display
Once the reason was hunted down the code changes were minimal. The label was changed for the interviewee image, which was triggering the download. The new label no longer includes `Narrator` which triggers the download.
The TEI xml transcript label was updated from `display label` to `timed log`, and an extra check was added to only include xml documents.
To test:
- Run tests via `docker compose exec django python manage.py test`, all should pass. Tests previously existed for transcripts and image, but the label check was corrected
- View [an …
=> Updated TEI and image OAI feed to match public site display assumptions

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/ImageFileHandler.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py
Implements [SYS-1531](https://uclalibrary.atlassian.net/browse/SYS-1531)
Currently, the OH staff application creates both submaster and thumbnail derivative images in the same way: resize the image such that the longest dimension is the maximum size for the derivative type (750 px for submasters, 200 px for thumbnails), maintaining the aspect ratio. 
This PR changes the way that thumbnails are generated. Now, thumbnails are always 200x200 squares, with black bars vertically or horizontally bordering the resized image to fill any extra space. Example images are included on the [Jira ticket](https://uclalibrary.atlassian.net/browse/SYS-1531).
This is a small code change done entirely within the `ImageFileHandler` class. An additional test image (public domain, from Wikimedia Commons) is …
=> SYS-1531: Make square thumbnails

.docker-compose_django.env, README.md, charts/Chart.yaml, charts/prod-ohstaff-values.yaml, charts/templates/configmap.yaml, charts/values.yaml, oh_staff_ui/management/commands/process_file.py, oh_staff_ui/models.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py, oh_staff_ui/urls.py, project/settings.py
Implements [SYS-934](https://uclalibrary.atlassian.net/browse/SYS-934).  Bumps version to `v1.1.0` for deployment; requires `gitops_kubernetes` update as well due to chart changes.
This PR adds the ability to access master files via the staff interface.  Caveat: this **should** work in the production environment... but I won't be sure until it's deployed.
Master files now have links on the `upload_file` page, which should allow direct viewing / download depending on browser settings.  These files are served via Django's [MEDIA_URL](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-MEDIA_URL) setting, which allows Django to serve user-uploaded files.  Normally this should not be done in production, but the use case for Oral History staff (infrequent non-public need) is …
=> SYS-934: Enable access to master files

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py, oh_staff_ui/urls.py
Fixes a problem with [SYS-934](https://uclalibrary.atlassian.net/browse/SYS-934).  Bumps version to `v1.1.1` for deployment.
This PR should fix a problem caused by my misunderstanding of how media (user-uploaded) files are handled by Django in production environments, when `DEBUG=False`.  It uses Django's built-in view `django.views.static.serve()` to serve files in `MEDIA_ROOT`... which is similar to what I was doing before, via a different built-in view which I thought was a short-cut for this functionality.  Apparently serving via `MEDIA_URL` is not allowed in production, but serving files from the place `MEDIA_URL` points to... is.
Along with this minor change in `urls.py`, I added a test which forces simulation of production mode `(RUN_ENV="prod", DEBUG=False)` and uses Django's …
=> SYS-934: Fix master file access in production

charts/prod-ohstaff-values.yaml, oh_staff_ui/management/commands/reprocess_derivative_images.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py, oh_staff_ui/views.py
Implements [SYS-1601](https://uclalibrary.atlassian.net/browse/SYS-1601)
Adds a new Django management command, `reprocess_derivative_images`. This command takes one optional argument, `--project_item_id`. If supplied, only images associated with the specified ProjectItem will be reprocessed. Otherwise, all images will be processed. Example usage: ```docker-compose exec django python manage.py reprocess_derivative_images --project_item_id 10331```
This command simply creates new derivative images from all master images instead of attempting to determine which ones require correction. This is simpler, and has the advantage that the new derivative images are now correctly associated with their respective masters through the `parent` field. The "created by" metadata is altered for the …
=> SYS-1601: add reprocess_derivative_images command

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/ImageFileHandler.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html
Fixes [SYS-1614](https://uclalibrary.atlassian.net/browse/SYS-1614).  Bumps version to `v1.1.3`  for deployment.
This PR fixes a bug in the `ImageFileHandler` class.  It was not accounting for non-default orientation as indicated by EXIF data.  This resulted in derivative images also having non-default orientation, usually rotated 90 degrees clockwise or counter-clockwise.  It only applied to about a dozen images, but those which are published to the public site looked bad.
The `ImageFileHandler` fix is not retroactive, so I'll need to copy a targeted fix-it script to the production environment and run it there.
[SYS-1614]: https://uclalibrary.atlassian.net/browse/SYS-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SYS-1614: Fix orientation problem with images

charts/prod-ohstaff-values.yaml, oh_staff_ui/management/commands/audit_media_files.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html
Implements [SYS-1098](https://uclalibrary.atlassian.net/browse/SYS-1098).  Bumps version to `v1.1.4` for deployment.
This PR adds a management command, `audit_media_files`.  It compares information about media files and reports differences via the application log.  It takes one mandatory argument:
* `DB`: Check all `MediaFile` objects and report on any where the real file pointed to does not exist, or has a different size from what's in the database
* 'FILES': Check all real files in `MEDIA_ROOT` (and all subdirectories) and report on any where there is no corresponding `MediaFile` object
* Also reports if there are multiple `MediaFile` objects matching the real file, which should not happen but... who knows?
* `ALL`: Runs both the `DB` and the `FILES` audits
Mismatches are reported via …
=> SYS-1098: Add file audit management command

charts/prod-ohstaff-values.yaml, oh_staff_ui/management/commands/audit_media_files.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html
Related to [SYS-1098](https://uclalibrary.atlassian.net/browse/SYS-1098).  Bumps version to `v1.1.5` for deployment.
This PR fixes a problem with the `audit_media_files` command.  Previously, it scanned all subdirectories of `MEDIA_ROOT`.  In our production environment, that is `/media`... which also has `OH_SOURCE` mounted in it as `/media/oh_source/upload`.  `/media/oh_source/` has hundreds of thousands of files which are not relevant for auditing.
`audit_media_files` now limits its scans to files in these 3 subdirectories of `MEDIA_ROOT`:
`settings.OH_MASTERS, settings.OH_STATIC, settings.OH_WOWZA`
@ztucker4 FYI, I'm merging this without review; tested locally to confirm correct behavior.
[SYS-1098]: https://uclalibrary.atlassian.net/browse/SYS-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> SYS-1098: Limit audit_media_files scan to master and derivative directories

charts/prod-ohstaff-values.yaml, oh_staff_ui/management/commands/audit_media_files.py
The `.snapshot` subdirectories created by our backup system also need to be excluded.  This PR adds a helper generator function to obtain the items in a directory tree, with the ability to exclude a list of subdirectories (currently, `oh_source` and `.snapshot`).
Tested locally by adding several unwanted subdirectories containing thousands of files.  Confirmed these subdirectories are skipped, with no noticeable impact on performance.
@ztucker4 FYI, merging this directly.
=> SYS-1098: Limit audit_media_files scan to master and derivative directories, better this time

charts/prod-ohstaff-values.yaml, oh_staff_ui/management/commands/audit_media_files.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/templates/oh_staff_ui/upload_file.html, oh_staff_ui/tests.py, oh_staff_ui/urls.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py, static/css/style.css, static/js/main.js
Implements [SYS-1598](https://uclalibrary.atlassian.net/browse/SYS-1598), which absorbed [SYS-1599](https://uclalibrary.atlassian.net/browse/SYS-1599)
This PR allows users to delete files (both Master and derivative) from item records. Users in the Oral History Staff user group will see a new column in the "File Information" table on `/upload_file/` pages containing a delete button for every file. When clicked, this button brings up a popup asking the user to confirm deletion of the selected file and its children (if any). If "Yes" is selected in this popup, the new `delete_file()` view is called and the relevant MediaFile(s), File object(s), and file(s) on disk are deleted. 
Also includes release note and tag bump for deployment, and two new tests for the new `delete_file_and_children()` …
=> SYS-1598: allow deletion of derivative media files

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py, oh_staff_ui/urls.py, oh_staff_ui/views.py, requirements.txt
Implements [SYS-1612](https://uclalibrary.atlassian.net/browse/SYS-1612) and [SYS-1621](https://uclalibrary.atlassian.net/browse/SYS-1621), with other minor changes.  Tagged as version `v1.1.7` for deployment.
This PR primarily fixes two bugs:
1. Prevents master file downloads by anonymous users.  The generic static `serve` view used with `media/` paths is now wrapped by a custom `serve_media_files` view, which requires login.  Otherwise, anyone who could figure out a URL for a master file could download it from anywhere.  There also are tests covering this now.
2. Enforces correct authorization for the `delete_file` view. The check for group membership has been added to the view itself, and a `PermissionDenied` exception is raised with HTTP 403 (and message logged) if violated.  This …
=> Security fixes

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/templates/oh_staff_ui/upload_file.html, oh_staff_ui/tests.py, oh_staff_ui/urls.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py, static/js/main.js
Implements [SYS-1600](https://uclalibrary.atlassian.net/browse/SYS-1600)
Adds the ability to delete ProjectItems without dependencies for users in the OH Staff user group. Users in this group will see a "Delete item" link within the "Item Actions" area of `edit_item` pages. Clicking this link will bring up a "Delete Item" modal. If the item has child ProjectItems or associated MediaFiles, the modal informs the user of these dependencies and the user has no option to delete. If the item can be deleted, the user is given the choice to "Delete" or "Cancel", with "Cancel" as the default. After deletion, if the item had a parent, the user is redirected to the parent's `edit_item` page. If not, the user is redirected to `item_search`. 
The underlying deletion view (`delete_item`) enforces that …
=> SYS-1600: allow deletion of item records

.docker-compose_django.env, charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/AudioFileHandler.py, oh_staff_ui/classes/OralHistoryFile.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html
Implements [SYS-1609](https://uclalibrary.atlassian.net/browse/SYS-1609).  Bumps version to `v1.1.9` for deployment.
This PR improves handling of `MediaFile` creation, which all happens via `OralHistoryFile.process_media_files()`.  `MediaFile` creation now is wrapped in a `try` block which catches generic `OSError`s. This should handle errors with permissions, non-existent directories which can't be created by Django, and full disks.  These are now caught, logged, stored in the database as `MediaFileError`s to display in the UI, and then re-raised as `ValueError` to be handled gracefully by the UI.
It also fixes a small bug in `AudioFileHandler` where what should have been a multi-line string was actually two strings, so the second one was ignored.
Finally, it changes `MEDIA_ROOT` in the …
=> SYS-1609: Improve logging for file creation failures

charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/edit_item.html, oh_staff_ui/templates/oh_staff_ui/release_notes.html, static/css/style.css
Implements [SYS-1630](https://uclalibrary.atlassian.net/issues/SYS-1630)
Makes a few CSS and HTML changes to fix alignment issues in the main `edit_item` form. 
`vertical-align: baseline` is implemented differently in different browsers, so this has been removed in favor of `vertical-align: top` (for labels and form fields) and `vertical-align: middle` (for buttons and checkboxes). To support this, the class name `form-checkbox` was added to table cells containing “Delete?” checkboxes in the `edit_item` template. Some CSS was also added to override default Bootstrap behavior for form fields.
I was not able to replicate the level of misalignment shown in the screenshot on the ticket (tried in Firefox, Chrome, and Safari on Mac at various window sizes), so please take a look at a few …
=> SYS-1630: fix alignment on edit_item form

charts/prod-ohstaff-values.yaml, oh_staff_ui/classes/OralHistoryMods.py, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/tests.py
Implements [SYS-1637](https://uclalibrary.atlassian.net/browse/SYS-1637).  Bumps version to `v1.1.11` for deployment.
This PR fixes a bug which allowed URLs for master files to be included in the OAI feed.  These files are accessible only via the staff UI, so including URLs for them is not appropriate for OAI content or the public site.
The fix makes relevant methods in the `OralHistoryMods` class more specific, so only file URLs for submasters are included in the OAI feed's MODs records.  A new test is added which confirms master file URLs are not included.
Confirm all 112 tests pass.  No need for more specific testing.
Locally, I grabbed before and after versions of 2 records and compared them:
```
$ diff zz002kppdz_before.xml zz002kppdz_after.xml
3c3
< …
```
=> SYS-1637: Remove master file URLs from OAI feed

charts/prod-ohstaff-values.yaml, oh_staff_ui/forms.py, oh_staff_ui/templates/oh_staff_ui/item_search.html, oh_staff_ui/templates/oh_staff_ui/release_notes.html, oh_staff_ui/templates/oh_staff_ui/search_results.html, oh_staff_ui/urls.py, oh_staff_ui/views.py, oh_staff_ui/views_utils.py, static/js/main.js, static/js/validation.js
Implements [SYS-1632](https://uclalibrary.atlassian.net/browse/SYS-1632) (mostly)
This PR adds two new functionalities to item search, which I believe satisfy [Lisa's requests](https://uclalibrary.atlassian.net/wiki/spaces/DEV/pages/276529172/OH+Staff+UI+Phase+3):
* Search filters for Item Type and Media File type. These can be used in conjunction with any search type to return only items with the specified Item Type or with attached Media Files of the specified type.
* Wildcard search. Searching for `*` will now return all items matching the filters. There is some simple JS validation to prevent users from performing a wildcard search without any filters (though the URL path `search_results/title/all/all/*` still exists and works).
I also have a few questions:
* This PR does not support …
=> SYS-1632: improve searching options

.github/workflows/build_docker_hub.yml, Dockerfile, charts/prod-ohstaff-values.yaml, docker-compose.yml, docker-compose_REMOTE.yml, oh_staff_ui/templates/oh_staff_ui/release_notes.html, requirements.txt
Implements [SYS-1674](https://uclalibrary.atlassian.net/browse/SYS-1674)
Upgrades without functionality changes. Includes:
* Base image updated to use Debian 12 and Python 3.12
* Django updated to 4.2.16, addressing [Dependabot alerts](https://github.com/UCLALibrary/oral-history-staff-ui/security/dependabot)
* Added new package to `requirements.txt`. `eulxml` requires the `pkg_resources` module, which is distributed with `setuptools`, which was included in Python 3.11 but not in 3.12
* Removed version declaration from docker-compose files
* Updated workflows to use latest actions versions and add scan tag to Docker Hub image
* Updated release notes and tag bump for deployment
Build logs should be clean: `docker compose --progress plain build > build.log`
112 tests should pass: …
=> SYS-1674: security fixes for OH Staff UI

README.md, charts/prod-ohstaff-values.yaml, oh_staff_ui/templates/oh_staff_ui/release_notes.html, requirements.txt
Implements [SYS-1753](https://uclalibrary.atlassian.net/browse/SYS-1753)
- Updated Django to 4.2.19 to patch security issues
- Bumped Helm chart version tag
- Added release note
- Updated `README.md`
- **Note:** the steps given to import data pointed to the `export_scripts` directory, but it looks like those data files are actually under `migration_data`)
**Testing**
✅ All tests passed in dev environment
[SYS-1753]: https://uclalibrary.atlassian.net/browse/SYS-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SYS-1753: Update Django to 4.2.19 to patch security issues and update README

.docker-compose_db.env, Dockerfile, charts/prod-ohstaff-values.yaml, docker-compose.yml, docker_scripts/entrypoint.sh, oh_staff_ui/templates/oh_staff_ui/base.html, oh_staff_ui/templates/oh_staff_ui/release_notes.html, requirements.txt, static/css/style.css, templates/admin/base_site.html
Implements [SYS-1829](https://uclalibrary.atlassian.net/browse/SYS-1829)
Includes necessary changes to upgrade to Django 5.2, Python 13, and PostgreSQL 16.
* `psycopg2` is replaced by `psycopg`
* `pillow` is updated to version 11.2.1 to support Python 13
*  Release notes are updated, and tag is bumped for deployment
Code changes in the app are all related to logout functionality. Per the [5.0 release notes](https://docs.djangoproject.com/en/5.2/releases/5.0/), "Support for logging out via GET requests in the django.contrib.auth.views.LogoutView and django.contrib.auth.views.logout_then_login() is removed." Therefore, `oh_staff_ui/templates/oh_staff_ui/base.html` is updated to change the "Logout" link to a form with a button that submits a POST request to the logout view. CSS is updated in …
=> SYS-1829: Update Django, Python, and PostgreSQL
